#!/usr/bin/env bash

HOST=`hostname`
if [[ ! -z "$1" ]]; then
	HOST=$1
fi

if [[ ! -e "hosts/$HOST/configuration.nix" ]]; then
	echo "missing hosts/$HOST/configuration.nix" >&2
	exit 1
fi

ln -sf "hosts/$HOST/configuration.nix" .
