#!/usr/bin/env python3

import argparse
import json
import os
import platform
import subprocess
import sys

def main(args):
    same_host = args.hostname == platform.node()

    priv_run = []

    # We only need to run privileged on the same host, otherwise we need to ssh as root 😿
    if same_host:
        priv_run = ['sudo']

    # Print build logs
    nix_args = ['-L']
    if args.nixpkgs:
        nix_args += ['--override-input', 'nixpkgs', args.nixpkgs, '--no-write-lock-file']
    if args.keep_going:
        nix_args += ['--keep-going']

    if not same_host:
        connection_string = json.loads(subprocess.check_output(['nix', 'eval', '--json', '--impure', '--expr', f'(import ./hosts/list.nix).nixos.{args.hostname}.connectionString or null']))

        if not connection_string:
            print(f'No connection string defined in hosts/list.nix for host {args.hostname}', file=sys.stderr)
            sys.exit(1)

        nix_args += ['--target-host', connection_string, '--build-host', 'localhost']

    path = os.getcwd()
    attr = f'{path}#{args.hostname}'

    nix_shell = priv_run + ['nixos-rebuild'] + nix_args + ['--flake', attr] + [f'{args.action}']

    os.execvp(nix_shell[0], nix_shell)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Rebuild system')
    parser.add_argument('--nixpkgs', dest='nixpkgs', help='Override the nixpkgs flake input with this path', nargs='?')
    parser.add_argument('--keep-going', '-k', dest='keep_going', action='store_true', help='Do not stop after first failure')
    parser.add_argument('hostname', help='Host whose configuration should we rebuild', nargs='?', default=platform.node())
    parser.add_argument('action', choices=['switch', 'boot', 'test'])

    args = parser.parse_args()

    main(args)
